
// This is a placeholder service that will eventually connect to your EcoChat.py backend
// For now, it provides mock responses to demonstrate the UI functionality

import { toast } from "@/hooks/use-toast";

interface ChatRequest {
  message: string;
  history?: Array<{
    role: "user" | "assistant";
    content: string;
  }>;
}

interface ChatResponse {
  response: string;
  sources?: string[];
}

// Sample knowledge base for mock responses
const knowledgeBase = {
  "carbon footprint": "Carbon footprint is the total amount of greenhouse gases that are generated by our actions. The average person's carbon footprint is about 4 tons per year. You can reduce your carbon footprint by using public transportation, reducing meat consumption, and choosing energy-efficient appliances.",
  "sustainable food": "Food choices have a significant impact on your carbon footprint. Plant-based diets generally have a lower carbon footprint than meat-heavy diets. Beef and lamb are particularly carbon-intensive. Consider reducing your meat consumption and opting for locally-grown, seasonal produce when possible.",
  "renewable energy": "Switching to renewable energy sources like solar or wind power can significantly reduce your carbon footprint. You can also reduce your energy consumption by using energy-efficient appliances, turning off lights and electronics when not in use, and improving your home's insulation.",
  "air travel": "Air travel has a significant carbon footprint. A single round-trip flight from New York to London emits about 1.5 tons of CO2 per passenger. Consider alternatives like video conferencing or train travel when possible, and if you must fly, consider offsetting your emissions through verified carbon offset programs.",
  "commute": "The carbon footprint of your daily commute depends on your mode of transportation and distance. Driving a gasoline car produces about 0.4 kg of CO2 per mile. Consider carpooling, using public transportation, biking, or walking to reduce your commute's environmental impact.",
};

export const sendChatMessage = async (chatRequest: ChatRequest): Promise<ChatResponse> => {
  try {
    // Mock API delay
    await new Promise(resolve => setTimeout(resolve, 1500));
    
    // Try to connect to your actual backend when it's available
    // const response = await fetch('http://your-backend-url/chat', {
    //   method: 'POST',
    //   headers: {
    //     'Content-Type': 'application/json',
    //   },
    //   body: JSON.stringify(chatRequest),
    // });
    
    // if (!response.ok) {
    //   throw new Error(`Error: ${response.status}`);
    // }
    
    // return await response.json();
    
    // For now, generate a mock response based on the input
    const message = chatRequest.message.toLowerCase();
    let responseText = "";
    
    // Check if the message contains any keywords from our knowledge base
    for (const [keyword, response] of Object.entries(knowledgeBase)) {
      if (message.includes(keyword)) {
        responseText = response;
        break;
      }
    }
    
    // Default response if no match found
    if (!responseText) {
      responseText = "That's an interesting question about sustainability! While I'm just a demo version with limited knowledge, I'm designed to provide information on various sustainability topics, calculate emissions for specific activities, and offer personalized recommendations based on your lifestyle.";
    }
    
    return {
      response: responseText,
      sources: ["Demo Knowledge Base"]
    };
  } catch (error) {
    console.error("Error in ecoChatService:", error);
    toast({
      title: "Service Error",
      description: "Failed to process your request",
      variant: "destructive",
    });
    throw error;
  }
};
